/**
 * @fileoverview Device controller - Generated by VIIS API Generator
 */

import { Request, Response } from 'express';
import { Inject } from 'typedi';
import { BaseController } from './base.controller';
import { Controller } from '../decorators/controller.decorator';
import { RouteDefinition } from '../types/common.types';
import { DeviceService } from '../services/device.service';
import { DeviceValidator } from '../validators/device.validator';
import { Node } from 'node-red';
import { ApiConfigManager } from '../config/api.config';

@Controller('/devices')
export class DeviceController extends BaseController {
    constructor(
        @Inject() private deviceService: DeviceService,
        @Inject() private deviceValidator: DeviceValidator,
        @Inject('node') node: Node,
        @Inject('configManager') configManager: ApiConfigManager
    ) {
        super(node, configManager);
    }

    getRoutes(): RouteDefinition[] {
        return [
            {
                method: 'GET',
                path: '/devices',
                handler: 'listDevices',
                middleware: ['auth']
            },
            {
                method: 'GET',
                path: '/devices/:id',
                handler: 'getDevice',
                middleware: ['auth']
            },
            {
                method: 'POST',
                path: '/devices',
                handler: 'createDevice',
                middleware: ['auth']
            },
            {
                method: 'PUT',
                path: '/devices/:id',
                handler: 'updateDevice',
                middleware: ['auth']
            },
            {
                method: 'DELETE',
                path: '/devices/:id',
                handler: 'deleteDevice',
                middleware: ['auth']
            }
        ];
    }


    /**
     * List devices
     */
    listDevices = this.asyncHandler(async (req: Request, res: Response): Promise<void> => {
        const { page, limit, offset } = this.getPaginationParams(req);
        
        const result = await this.executeOperation(
            'listDevices',
            () => this.deviceService.list({ page, limit, offset })
        );
        
        this.success(res, result, 200, 'Devices retrieved successfully');
    }, 'listDevices');

    /**
     * Get device by ID
     */
    getDevice = this.asyncHandler(async (req: Request, res: Response): Promise<void> => {
        const { id } = req.params;
        this.validateString(id, 'id');
        
        const result = await this.executeOperation(
            'getDevice',
            () => this.deviceService.getById(id)
        );
        
        if (!result) {
            return this.notFoundError(res, 'Device not found');
        }
        
        this.success(res, result, 200, 'Device retrieved successfully');
    }, 'getDevice');

    /**
     * Create new device
     */
    createDevice = this.asyncHandler(async (req: Request, res: Response): Promise<void> => {
        const data = await this.deviceValidator.validateCreate(req.body);
        
        const result = await this.executeOperation(
            'createDevice',
            () => this.deviceService.create(data)
        );
        
        this.success(res, result, 201, 'Device created successfully');
    }, 'createDevice');

    /**
     * Update device
     */
    updateDevice = this.asyncHandler(async (req: Request, res: Response): Promise<void> => {
        const { id } = req.params;
        this.validateString(id, 'id');
        
        const data = await this.deviceValidator.validateUpdate(req.body);
        
        const result = await this.executeOperation(
            'updateDevice',
            () => this.deviceService.update(id, data)
        );
        
        this.success(res, result, 200, 'Device updated successfully');
    }, 'updateDevice');

    /**
     * Delete device
     */
    deleteDevice = this.asyncHandler(async (req: Request, res: Response): Promise<void> => {
        const { id } = req.params;
        this.validateString(id, 'id');
        
        await this.executeOperation(
            'deleteDevice',
            () => this.deviceService.delete(id)
        );
        
        this.success(res, { message: 'Device deleted successfully' }, 200);
    }, 'deleteDevice');
}