/**
 * @fileoverview Device types - Generated by VIIS API Generator
 */

export interface Device {
    id: string;
    // TODO: Add your entity properties here
    createdAt?: Date;
    updatedAt?: Date;
}

export interface CreateDeviceRequest {
    // TODO: Add properties required for creation
}

export interface UpdateDeviceRequest {
    // TODO: Add properties that can be updated
}

export interface DeviceListResponse {
    data: Device[];
    pagination: {
        page: number;
        limit: number;
        total: number;
        totalPages: number;
    };
}