/**
 * @fileoverview Device types - Generated by VIIS API Generator
 */

export interface Device {
    id: string;
    name: string;
    description?: string;
    status?: string;
    customerId?: string;
    createdAt?: Date;
    updatedAt?: Date;
}

export interface CreateDeviceRequest {
    name: string;
    description?: string;
    status?: string;
    customerId?: string;
}

export interface UpdateDeviceRequest {
    name?: string;
    description?: string;
    status?: string;
}

export interface DeviceListResponse {
    data: Device[];
    pagination: {
        page: number;
        limit: number;
        total: number;
        totalPages: number;
    };
}