/**
 * @fileoverview Tung types - Generated by VIIS API Generator
 */

export interface Tung {
    id: string;
    name: string;
    description?: string;
    status?: string;
    // TODO: Add your entity properties here
    createdAt?: Date;
    updatedAt?: Date;
}

export interface CreateTungRequest {
    name: string;
    description?: string;
    status?: string;
    // TODO: Add properties required for creation
}

export interface UpdateTungRequest {
    name?: string;
    description?: string;
    status?: string;
    // TODO: Add properties that can be updated
}

export interface TungListResponse {
    data: Tung[];
    pagination: {
        page: number;
        limit: number;
        total: number;
        totalPages: number;
    };
}