/**
 * @fileoverview tungtran types - Generated by VIIS API Generator
 */

export interface tungtran {
    id: string;
    name: string;
    description?: string;
    status?: string;
    // TODO: Add your entity properties here
    createdAt?: Date;
    updatedAt?: Date;
}

export interface CreatetungtranRequest {
    name: string;
    description?: string;
    status?: string;
    // TODO: Add properties required for creation
}

export interface UpdatetungtranRequest {
    name?: string;
    description?: string;
    status?: string;
    // TODO: Add properties that can be updated
}

export interface tungtranListResponse {
    data: tungtran[];
    pagination: {
        page: number;
        limit: number;
        total: number;
        totalPages: number;
    };
}