import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrate1742199337107 implements MigrationInterface {
    name = 'Migrate1742199337107'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` DROP FOREIGN KEY \`fk_plan_id\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` DROP FOREIGN KEY \`tabiot_schedule_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP FOREIGN KEY \`fk_schedule_id\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` DROP FOREIGN KEY \`tabiot_production_function_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` DROP FOREIGN KEY \`tabiot_device_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_telemetry\` DROP FOREIGN KEY \`tabiot_device_telemetry_ibfk_1\``);
        await queryRunner.query(`DROP INDEX \`device_id\` ON \`tabiot_schedule\``);
        await queryRunner.query(`DROP INDEX \`device_profile_id\` ON \`tabiot_production_function\``);
        await queryRunner.query(`DROP INDEX \`idx_identifier\` ON \`tabiot_production_function\``);
        await queryRunner.query(`DROP INDEX \`device_profile_id\` ON \`tabiot_device\``);
        await queryRunner.query(`DROP INDEX \`device_id\` ON \`tabiot_device_telemetry\``);
        await queryRunner.query(`DROP INDEX \`unique_device_key_timestamp\` ON \`tabiot_device_telemetry\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` ADD \`_user_tags\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` ADD \`_comments\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` ADD \`_assign\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` ADD \`_liked_by\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` ADD \`modified_by\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` ADD \`owner\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` ADD \`docstatus\` smallint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` ADD \`idx\` bigint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` ADD \`deleted\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` ADD \`_user_tags\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` ADD \`_comments\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` ADD \`_assign\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` ADD \`_liked_by\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` ADD \`modified_by\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` ADD \`owner\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` ADD \`docstatus\` smallint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` ADD \`idx\` bigint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` ADD \`deleted\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`_user_tags\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`_comments\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`_assign\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`_liked_by\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`modified_by\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`owner\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`docstatus\` smallint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`idx\` bigint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`deleted\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` ADD \`_user_tags\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` ADD \`_comments\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` ADD \`_assign\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` ADD \`_liked_by\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` ADD \`modified_by\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` ADD \`owner\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` ADD \`docstatus\` smallint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` ADD \`idx\` bigint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` ADD \`deleted\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` ADD \`_user_tags\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` ADD \`_comments\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` ADD \`_assign\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` ADD \`_liked_by\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` ADD \`modified_by\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` ADD \`owner\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` ADD \`docstatus\` smallint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` ADD \`idx\` bigint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` ADD \`deleted\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` ADD \`_user_tags\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` ADD \`_comments\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` ADD \`_assign\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` ADD \`_liked_by\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` ADD \`modified_by\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` ADD \`owner\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` ADD \`docstatus\` smallint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` ADD \`idx\` bigint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` ADD \`deleted\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`device_offline_automation_intents\` ADD \`_user_tags\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`device_offline_automation_intents\` ADD \`_comments\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`device_offline_automation_intents\` ADD \`_assign\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`device_offline_automation_intents\` ADD \`_liked_by\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`device_offline_automation_intents\` ADD \`modified_by\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`device_offline_automation_intents\` ADD \`owner\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`device_offline_automation_intents\` ADD \`docstatus\` smallint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`device_offline_automation_intents\` ADD \`idx\` bigint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`device_offline_automation_intents\` ADD \`deleted\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` CHANGE \`creation\` \`creation\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` CHANGE \`modified\` \`modified\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` CHANGE \`schedule_count\` \`schedule_count\` int NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` CHANGE \`is_synced\` \`is_synced\` tinyint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` CHANGE \`is_from_local\` \`is_from_local\` int NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` CHANGE \`is_deleted\` \`is_deleted\` tinyint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` CHANGE \`creation\` \`creation\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` CHANGE \`modified\` \`modified\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` CHANGE \`enable\` \`enable\` tinyint NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` CHANGE \`type\` \`type\` enum ('', 'circulate', 'period', 'fixed', 'interval') NOT NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` CHANGE \`is_deleted\` \`is_deleted\` tinyint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` CHANGE \`status\` \`status\` enum ('running', 'stopped', 'finished', '') NOT NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`creation\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`creation\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`modified\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`modified\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`start_time\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`start_time\` time NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`end_time\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`end_time\` time NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` CHANGE \`creation\` \`creation\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` CHANGE \`modified\` \`modified\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` CHANGE \`is_default\` \`is_default\` tinyint NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` CHANGE \`creation\` \`creation\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` CHANGE \`modified\` \`modified\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` CHANGE \`data_type\` \`data_type\` enum ('Bool', 'Value', 'Enum', 'Raw', 'String', 'Group Break', 'Tab Break', 'IP', 'Checkbox-bit', 'User data type') NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` CHANGE \`show_chart\` \`show_chart\` tinyint NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` CHANGE \`creation\` \`creation\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` CHANGE \`modified\` \`modified\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` ADD UNIQUE INDEX \`IDX_beafdcdca7e045dfb0d68d370f\` (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` CHANGE \`is_gateway\` \`is_gateway\` tinyint NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_telemetry_latest\` CHANGE \`boolean_value\` \`boolean_value\` tinyint NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_telemetry\` CHANGE \`boolean_value\` \`boolean_value\` tinyint NULL`);
        await queryRunner.query(`ALTER TABLE \`device_offline_automation_intents\` CHANGE \`creation\` \`creation\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`device_offline_automation_intents\` CHANGE \`modified\` \`modified\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`device_offline_automation_intents\` CHANGE \`enable\` \`enable\` tinyint NOT NULL DEFAULT '1'`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_10ebf866c92988aca3a3e94129\` ON \`tabiot_device_telemetry\` (\`device_id\`, \`timestamp\`, \`key_name\`)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` ADD CONSTRAINT \`FK_4f3fa51bdcb252c4869ac67c8ae\` FOREIGN KEY (\`schedule_plan_id\`) REFERENCES \`tabiot_schedule_plan\`(\`name\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD CONSTRAINT \`FK_82dbff0216b4f3ef0f543d2c07b\` FOREIGN KEY (\`schedule_id\`) REFERENCES \`tabiot_schedule\`(\`name\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` ADD CONSTRAINT \`FK_9fc556cd6d9ccfdd305e9f77f25\` FOREIGN KEY (\`device_profile_id\`) REFERENCES \`tabiot_device_profile\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` ADD CONSTRAINT \`FK_803f66858054f399391d92e5f98\` FOREIGN KEY (\`device_profile_id\`) REFERENCES \`tabiot_device_profile\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_telemetry_latest\` ADD CONSTRAINT \`FK_47ac20dfac901a971b28b5d4ea3\` FOREIGN KEY (\`device_id\`) REFERENCES \`tabiot_device\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_telemetry\` ADD CONSTRAINT \`FK_26704df8a691ecb44c435e87ef9\` FOREIGN KEY (\`device_id\`) REFERENCES \`tabiot_device\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`device_offline_automation_intents\` ADD CONSTRAINT \`FK_d8226ed2510b2417ad5d78edb00\` FOREIGN KEY (\`device_id\`) REFERENCES \`tabiot_device\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`device_offline_automation_intents\` DROP FOREIGN KEY \`FK_d8226ed2510b2417ad5d78edb00\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_telemetry\` DROP FOREIGN KEY \`FK_26704df8a691ecb44c435e87ef9\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_telemetry_latest\` DROP FOREIGN KEY \`FK_47ac20dfac901a971b28b5d4ea3\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` DROP FOREIGN KEY \`FK_803f66858054f399391d92e5f98\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` DROP FOREIGN KEY \`FK_9fc556cd6d9ccfdd305e9f77f25\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP FOREIGN KEY \`FK_82dbff0216b4f3ef0f543d2c07b\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` DROP FOREIGN KEY \`FK_4f3fa51bdcb252c4869ac67c8ae\``);
        await queryRunner.query(`DROP INDEX \`IDX_10ebf866c92988aca3a3e94129\` ON \`tabiot_device_telemetry\``);
        await queryRunner.query(`ALTER TABLE \`device_offline_automation_intents\` CHANGE \`enable\` \`enable\` tinyint(1) NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`device_offline_automation_intents\` CHANGE \`modified\` \`modified\` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`device_offline_automation_intents\` CHANGE \`creation\` \`creation\` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_telemetry\` CHANGE \`boolean_value\` \`boolean_value\` tinyint(1) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_telemetry_latest\` CHANGE \`boolean_value\` \`boolean_value\` tinyint(1) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` CHANGE \`is_gateway\` \`is_gateway\` tinyint NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` DROP INDEX \`IDX_beafdcdca7e045dfb0d68d370f\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` CHANGE \`modified\` \`modified\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` CHANGE \`creation\` \`creation\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` CHANGE \`show_chart\` \`show_chart\` tinyint(1) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` CHANGE \`data_type\` \`data_type\` enum ('Bool', 'Value', 'Enum', 'Raw', 'String', 'Group Break', 'Tab Break', 'IP', 'Checkbox-bit') NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` CHANGE \`modified\` \`modified\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` CHANGE \`creation\` \`creation\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` CHANGE \`is_default\` \`is_default\` tinyint(1) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` CHANGE \`modified\` \`modified\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` CHANGE \`creation\` \`creation\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`end_time\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`end_time\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`start_time\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`start_time\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`modified\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`modified\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`creation\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`creation\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` CHANGE \`status\` \`status\` enum ('running', 'stopped', 'finished', '') NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` CHANGE \`is_deleted\` \`is_deleted\` tinyint NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` CHANGE \`type\` \`type\` enum ('', 'circulate', 'period', 'fixed', 'interval') NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` CHANGE \`enable\` \`enable\` tinyint NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` CHANGE \`modified\` \`modified\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` CHANGE \`creation\` \`creation\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` CHANGE \`is_deleted\` \`is_deleted\` tinyint NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` CHANGE \`is_from_local\` \`is_from_local\` int NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` CHANGE \`is_synced\` \`is_synced\` tinyint NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` CHANGE \`schedule_count\` \`schedule_count\` int NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` CHANGE \`modified\` \`modified\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` CHANGE \`creation\` \`creation\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`device_offline_automation_intents\` DROP COLUMN \`deleted\``);
        await queryRunner.query(`ALTER TABLE \`device_offline_automation_intents\` DROP COLUMN \`idx\``);
        await queryRunner.query(`ALTER TABLE \`device_offline_automation_intents\` DROP COLUMN \`docstatus\``);
        await queryRunner.query(`ALTER TABLE \`device_offline_automation_intents\` DROP COLUMN \`owner\``);
        await queryRunner.query(`ALTER TABLE \`device_offline_automation_intents\` DROP COLUMN \`modified_by\``);
        await queryRunner.query(`ALTER TABLE \`device_offline_automation_intents\` DROP COLUMN \`_liked_by\``);
        await queryRunner.query(`ALTER TABLE \`device_offline_automation_intents\` DROP COLUMN \`_assign\``);
        await queryRunner.query(`ALTER TABLE \`device_offline_automation_intents\` DROP COLUMN \`_comments\``);
        await queryRunner.query(`ALTER TABLE \`device_offline_automation_intents\` DROP COLUMN \`_user_tags\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` DROP COLUMN \`deleted\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` DROP COLUMN \`idx\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` DROP COLUMN \`docstatus\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` DROP COLUMN \`owner\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` DROP COLUMN \`modified_by\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` DROP COLUMN \`_liked_by\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` DROP COLUMN \`_assign\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` DROP COLUMN \`_comments\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` DROP COLUMN \`_user_tags\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` DROP COLUMN \`deleted\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` DROP COLUMN \`idx\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` DROP COLUMN \`docstatus\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` DROP COLUMN \`owner\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` DROP COLUMN \`modified_by\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` DROP COLUMN \`_liked_by\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` DROP COLUMN \`_assign\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` DROP COLUMN \`_comments\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` DROP COLUMN \`_user_tags\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` DROP COLUMN \`deleted\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` DROP COLUMN \`idx\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` DROP COLUMN \`docstatus\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` DROP COLUMN \`owner\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` DROP COLUMN \`modified_by\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` DROP COLUMN \`_liked_by\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` DROP COLUMN \`_assign\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` DROP COLUMN \`_comments\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` DROP COLUMN \`_user_tags\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`deleted\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`idx\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`docstatus\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`owner\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`modified_by\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`_liked_by\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`_assign\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`_comments\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`_user_tags\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` DROP COLUMN \`deleted\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` DROP COLUMN \`idx\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` DROP COLUMN \`docstatus\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` DROP COLUMN \`owner\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` DROP COLUMN \`modified_by\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` DROP COLUMN \`_liked_by\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` DROP COLUMN \`_assign\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` DROP COLUMN \`_comments\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` DROP COLUMN \`_user_tags\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` DROP COLUMN \`deleted\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` DROP COLUMN \`idx\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` DROP COLUMN \`docstatus\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` DROP COLUMN \`owner\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` DROP COLUMN \`modified_by\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` DROP COLUMN \`_liked_by\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` DROP COLUMN \`_assign\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` DROP COLUMN \`_comments\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` DROP COLUMN \`_user_tags\``);
        await queryRunner.query(`CREATE UNIQUE INDEX \`unique_device_key_timestamp\` ON \`tabiot_device_telemetry\` (\`device_id\`, \`key_name\`, \`timestamp\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`device_id\` ON \`tabiot_device_telemetry\` (\`device_id\`, \`timestamp\`, \`key_name\`)`);
        await queryRunner.query(`CREATE INDEX \`device_profile_id\` ON \`tabiot_device\` (\`device_profile_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`idx_identifier\` ON \`tabiot_production_function\` (\`identifier\`)`);
        await queryRunner.query(`CREATE INDEX \`device_profile_id\` ON \`tabiot_production_function\` (\`device_profile_id\`)`);
        await queryRunner.query(`CREATE INDEX \`device_id\` ON \`tabiot_schedule\` (\`device_id\`)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_telemetry\` ADD CONSTRAINT \`tabiot_device_telemetry_ibfk_1\` FOREIGN KEY (\`device_id\`) REFERENCES \`tabiot_device\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` ADD CONSTRAINT \`tabiot_device_ibfk_1\` FOREIGN KEY (\`device_profile_id\`) REFERENCES \`tabiot_device_profile\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` ADD CONSTRAINT \`tabiot_production_function_ibfk_1\` FOREIGN KEY (\`device_profile_id\`) REFERENCES \`tabiot_device_profile\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD CONSTRAINT \`fk_schedule_id\` FOREIGN KEY (\`schedule_id\`) REFERENCES \`tabiot_schedule\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` ADD CONSTRAINT \`tabiot_schedule_ibfk_1\` FOREIGN KEY (\`device_id\`) REFERENCES \`tabiot_device\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` ADD CONSTRAINT \`fk_plan_id\` FOREIGN KEY (\`schedule_plan_id\`) REFERENCES \`tabiot_schedule_plan\`(\`name\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
