import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrate1749109890470 implements MigrationInterface {
    name = 'Migrate1749109890470'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` DROP FOREIGN KEY \`fk_plan_id\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` DROP FOREIGN KEY \`tabiot_schedule_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP FOREIGN KEY \`fk_schedule_id\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` DROP FOREIGN KEY \`tabiot_production_function_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` DROP FOREIGN KEY \`tabiot_customer_user_credentials_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP FOREIGN KEY \`tabiot_customer_user_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` DROP FOREIGN KEY \`tabiot_device_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_telemetry\` DROP FOREIGN KEY \`tabiot_device_telemetry_ibfk_1\``);
        await queryRunner.query(`DROP INDEX \`device_id\` ON \`tabiot_schedule\``);
        await queryRunner.query(`DROP INDEX \`device_profile_id\` ON \`tabiot_production_function\``);
        await queryRunner.query(`DROP INDEX \`idx_identifier\` ON \`tabiot_production_function\``);
        await queryRunner.query(`DROP INDEX \`user_id\` ON \`tabiot_customer_user_credentials\``);
        await queryRunner.query(`DROP INDEX \`customer_id\` ON \`tabiot_customer_user\``);
        await queryRunner.query(`DROP INDEX \`device_profile_id\` ON \`tabiot_device\``);
        await queryRunner.query(`DROP INDEX \`device_id\` ON \`tabiot_device_telemetry\``);
        await queryRunner.query(`CREATE TABLE \`customer_login_sessions\` (\`creation\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), \`modified\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`_user_tags\` text NULL, \`_comments\` text NULL, \`_assign\` text NULL, \`_liked_by\` text NULL, \`modified_by\` varchar(140) NULL, \`owner\` varchar(140) NULL, \`docstatus\` smallint NOT NULL DEFAULT '0', \`idx\` bigint NOT NULL DEFAULT '0', \`deleted\` datetime(6) NULL, \`name\` varchar(140) NOT NULL, \`user_id\` varchar(140) NULL, \`device\` varchar(255) NULL, \`ip_address\` varchar(45) NULL, \`login_time\` timestamp NOT NULL, \`logout_time\` timestamp NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, PRIMARY KEY (\`name\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tabiot_dynamic_role\` (\`creation\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), \`modified\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`_user_tags\` text NULL, \`_comments\` text NULL, \`_assign\` text NULL, \`_liked_by\` text NULL, \`modified_by\` varchar(140) NULL, \`owner\` varchar(140) NULL, \`docstatus\` smallint NOT NULL DEFAULT '0', \`idx\` bigint NOT NULL DEFAULT '0', \`deleted\` datetime(6) NULL, \`name\` varchar(140) NOT NULL, \`label\` varchar(140) NULL, \`role\` varchar(140) NULL, \`iot_customer\` varchar(140) NULL, \`sections\` text NULL, PRIMARY KEY (\`name\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`device_offline_automation_intents\` (\`creation\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), \`modified\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`_user_tags\` text NULL, \`_comments\` text NULL, \`_assign\` text NULL, \`_liked_by\` text NULL, \`modified_by\` varchar(140) NULL, \`owner\` varchar(140) NULL, \`docstatus\` smallint NOT NULL DEFAULT '0', \`idx\` bigint NOT NULL DEFAULT '0', \`deleted\` datetime(6) NULL, \`id\` varchar(36) NOT NULL, \`label\` varchar(255) NULL, \`enable\` tinyint NOT NULL DEFAULT '1', \`intent_json\` json NULL, \`device_id\` varchar(255) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` DROP COLUMN \`last_reset_password_key\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`created_time\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`customer_name\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`developer_mode\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`zip_code\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` ADD \`_user_tags\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` ADD \`_comments\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` ADD \`_assign\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` ADD \`_liked_by\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` ADD \`modified_by\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` ADD \`owner\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` ADD \`docstatus\` smallint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` ADD \`idx\` bigint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` ADD \`deleted\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` ADD \`_user_tags\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` ADD \`_comments\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` ADD \`_assign\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` ADD \`_liked_by\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` ADD \`modified_by\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` ADD \`owner\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` ADD \`docstatus\` smallint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` ADD \`idx\` bigint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` ADD \`deleted\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`_user_tags\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`_comments\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`_assign\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`_liked_by\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`modified_by\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`owner\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`docstatus\` smallint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`idx\` bigint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`deleted\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` ADD \`_user_tags\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` ADD \`_comments\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` ADD \`_assign\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` ADD \`_liked_by\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` ADD \`modified_by\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` ADD \`owner\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` ADD \`docstatus\` smallint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` ADD \`idx\` bigint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` ADD \`deleted\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` ADD \`_user_tags\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` ADD \`_comments\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` ADD \`_assign\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` ADD \`_liked_by\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` ADD \`modified_by\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` ADD \`owner\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` ADD \`docstatus\` smallint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` ADD \`idx\` bigint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` ADD \`deleted\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` ADD \`creation\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` ADD \`modified\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` ADD \`_user_tags\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` ADD \`_comments\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` ADD \`_assign\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` ADD \`_liked_by\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` ADD \`modified_by\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` ADD \`owner\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` ADD \`docstatus\` smallint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` ADD \`idx\` bigint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` ADD \`deleted\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` ADD \`id\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` ADD \`last_reset_password_key_generated_on\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`creation\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`modified\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`_user_tags\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`_comments\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`_assign\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`_liked_by\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`modified_by\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`owner\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`docstatus\` smallint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`idx\` bigint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`deleted\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`user_type\` enum ('VIIS_ROOT_USER', 'System User', 'TENANT_SUPER_ADMIN', 'TENANT_ADMIN', 'TENANT_USER', 'TENANT_CUSTOM_ROLE', 'Viis IoT User') NOT NULL DEFAULT 'Viis IoT User'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`role_label\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` ADD \`_user_tags\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` ADD \`_comments\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` ADD \`_assign\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` ADD \`_liked_by\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` ADD \`modified_by\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` ADD \`owner\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` ADD \`docstatus\` smallint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` ADD \`idx\` bigint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` ADD \`deleted\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` ADD \`customer_id\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`_user_tags\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`_comments\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`_assign\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`_liked_by\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`modified_by\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`owner\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`docstatus\` smallint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`idx\` bigint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`deleted\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`modifiedBy\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`id\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD UNIQUE INDEX \`IDX_34e197ebfce40659e171f68c58\` (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`customerName\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`createdTime\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`zipPostalCode\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`zipCode\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`packageId\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`developerMode\` smallint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`developerWebhookId\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`developerRuleId\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`test\` decimal(21,9) NOT NULL DEFAULT '0.000000000'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`isReceiveConnectionNoti\` smallint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`isReceiveNotificationNoti\` smallint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` CHANGE \`creation\` \`creation\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` CHANGE \`modified\` \`modified\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` CHANGE \`schedule_count\` \`schedule_count\` int NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` CHANGE \`status\` \`status\` enum ('active', 'inactive') NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` CHANGE \`is_synced\` \`is_synced\` tinyint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` CHANGE \`is_from_local\` \`is_from_local\` int NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` CHANGE \`is_deleted\` \`is_deleted\` tinyint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` CHANGE \`creation\` \`creation\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` CHANGE \`modified\` \`modified\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` CHANGE \`enable\` \`enable\` tinyint NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` CHANGE \`type\` \`type\` enum ('', 'circulate', 'period', 'fixed', 'interval') NOT NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` CHANGE \`is_deleted\` \`is_deleted\` tinyint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` CHANGE \`status\` \`status\` enum ('running', 'stopped', 'finished', '') NOT NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`creation\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`creation\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`modified\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`modified\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`start_time\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`start_time\` time NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`end_time\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`end_time\` time NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`start_time\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`start_time\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`end_time\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`end_time\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` CHANGE \`creation\` \`creation\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` CHANGE \`modified\` \`modified\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` CHANGE \`is_default\` \`is_default\` tinyint NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` CHANGE \`creation\` \`creation\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` CHANGE \`modified\` \`modified\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` CHANGE \`data_type\` \`data_type\` enum ('Bool', 'Value', 'Enum', 'Raw', 'String', 'Group Break', 'Tab Break', 'IP', 'Checkbox-bit', 'User data type') NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` CHANGE \`show_chart\` \`show_chart\` tinyint NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` ADD \`name\` varchar(140) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` DROP COLUMN \`enable\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` ADD \`enable\` smallint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` DROP COLUMN \`password\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` ADD \`password\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` ADD \`user_id\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` ADD UNIQUE INDEX \`IDX_e88c7a238c02307fa55aa10e6a\` (\`user_id\`)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` DROP COLUMN \`reset_password_key\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` ADD \`reset_password_key\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` DROP COLUMN \`total_retry_send_email\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` ADD \`total_retry_send_email\` bigint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`name\` varchar(140) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`user_id\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD UNIQUE INDEX \`IDX_72c84d7e5ad67e33989de07b8c\` (\`user_id\`)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`user_name\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`user_name\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`user_avatar\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`user_avatar\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`email\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`email\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`full_name\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`full_name\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`phone_number\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`phone_number\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`address\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`address\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`date_warranty\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`date_warranty\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`first_name\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`first_name\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`last_name\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`last_name\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`district\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`district\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`ward\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`ward\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`province\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`province\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`is_admin\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`is_admin\` smallint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`employee_id\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`employee_id\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`is_deactivated\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`is_deactivated\` smallint NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`customer_id\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`customer_id\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`iot_dynamic_role\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`iot_dynamic_role\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` CHANGE \`creation\` \`creation\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` CHANGE \`modified\` \`modified\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` ADD UNIQUE INDEX \`IDX_beafdcdca7e045dfb0d68d370f\` (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` CHANGE \`is_gateway\` \`is_gateway\` tinyint NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` CHANGE \`creation\` \`creation\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` CHANGE \`modified\` \`modified\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`name\` varchar(140) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`email\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`email\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`phone\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`phone\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`description\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`address\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`address\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`city\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`city\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`country\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`country\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`province\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`province\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`logo\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`logo\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`district\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`district\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`ward\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`ward\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`type\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`type\` varchar(140) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_telemetry_latest\` CHANGE \`boolean_value\` \`boolean_value\` tinyint NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_telemetry\` CHANGE \`boolean_value\` \`boolean_value\` tinyint NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_e88c7a238c02307fa55aa10e6a\` ON \`tabiot_customer_user_credentials\` (\`user_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`unique_user_id\` ON \`tabiot_customer_user\` (\`user_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_10ebf866c92988aca3a3e94129\` ON \`tabiot_device_telemetry\` (\`device_id\`, \`timestamp\`, \`key_name\`)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` ADD CONSTRAINT \`FK_4f3fa51bdcb252c4869ac67c8ae\` FOREIGN KEY (\`schedule_plan_id\`) REFERENCES \`tabiot_schedule_plan\`(\`name\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD CONSTRAINT \`FK_82dbff0216b4f3ef0f543d2c07b\` FOREIGN KEY (\`schedule_id\`) REFERENCES \`tabiot_schedule\`(\`name\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` ADD CONSTRAINT \`FK_9fc556cd6d9ccfdd305e9f77f25\` FOREIGN KEY (\`device_profile_id\`) REFERENCES \`tabiot_device_profile\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customer_login_sessions\` ADD CONSTRAINT \`FK_6796fe0549c819adab8f5154e46\` FOREIGN KEY (\`user_id\`) REFERENCES \`tabiot_customer_user\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` ADD CONSTRAINT \`FK_e88c7a238c02307fa55aa10e6ab\` FOREIGN KEY (\`user_id\`) REFERENCES \`tabiot_customer_user\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD CONSTRAINT \`FK_f09e5990e0e92e85ebca9cdc7aa\` FOREIGN KEY (\`customer_id\`) REFERENCES \`tabiot_customer\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD CONSTRAINT \`FK_780eb2884bf379e3f5744bdc0f1\` FOREIGN KEY (\`iot_dynamic_role\`) REFERENCES \`tabiot_dynamic_role\`(\`name\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` ADD CONSTRAINT \`FK_ca6a1941a27bc05174bddadc72a\` FOREIGN KEY (\`customer_id\`) REFERENCES \`tabiot_customer\`(\`name\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` ADD CONSTRAINT \`FK_803f66858054f399391d92e5f98\` FOREIGN KEY (\`device_profile_id\`) REFERENCES \`tabiot_device_profile\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_dynamic_role\` ADD CONSTRAINT \`FK_2dc9693c049f8f5d16128500584\` FOREIGN KEY (\`iot_customer\`) REFERENCES \`tabiot_customer\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_telemetry_latest\` ADD CONSTRAINT \`FK_47ac20dfac901a971b28b5d4ea3\` FOREIGN KEY (\`device_id\`) REFERENCES \`tabiot_device\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`device_offline_automation_intents\` ADD CONSTRAINT \`FK_d8226ed2510b2417ad5d78edb00\` FOREIGN KEY (\`device_id\`) REFERENCES \`tabiot_device\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_telemetry\` ADD CONSTRAINT \`FK_26704df8a691ecb44c435e87ef9\` FOREIGN KEY (\`device_id\`) REFERENCES \`tabiot_device\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`tabiot_device_telemetry\` DROP FOREIGN KEY \`FK_26704df8a691ecb44c435e87ef9\``);
        await queryRunner.query(`ALTER TABLE \`device_offline_automation_intents\` DROP FOREIGN KEY \`FK_d8226ed2510b2417ad5d78edb00\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_telemetry_latest\` DROP FOREIGN KEY \`FK_47ac20dfac901a971b28b5d4ea3\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_dynamic_role\` DROP FOREIGN KEY \`FK_2dc9693c049f8f5d16128500584\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` DROP FOREIGN KEY \`FK_803f66858054f399391d92e5f98\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` DROP FOREIGN KEY \`FK_ca6a1941a27bc05174bddadc72a\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP FOREIGN KEY \`FK_780eb2884bf379e3f5744bdc0f1\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP FOREIGN KEY \`FK_f09e5990e0e92e85ebca9cdc7aa\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` DROP FOREIGN KEY \`FK_e88c7a238c02307fa55aa10e6ab\``);
        await queryRunner.query(`ALTER TABLE \`customer_login_sessions\` DROP FOREIGN KEY \`FK_6796fe0549c819adab8f5154e46\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` DROP FOREIGN KEY \`FK_9fc556cd6d9ccfdd305e9f77f25\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP FOREIGN KEY \`FK_82dbff0216b4f3ef0f543d2c07b\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` DROP FOREIGN KEY \`FK_4f3fa51bdcb252c4869ac67c8ae\``);
        await queryRunner.query(`DROP INDEX \`IDX_10ebf866c92988aca3a3e94129\` ON \`tabiot_device_telemetry\``);
        await queryRunner.query(`DROP INDEX \`unique_user_id\` ON \`tabiot_customer_user\``);
        await queryRunner.query(`DROP INDEX \`REL_e88c7a238c02307fa55aa10e6a\` ON \`tabiot_customer_user_credentials\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_telemetry\` CHANGE \`boolean_value\` \`boolean_value\` tinyint(1) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_telemetry_latest\` CHANGE \`boolean_value\` \`boolean_value\` tinyint(1) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`type\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`type\` enum ('group', 'individual') NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`ward\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`ward\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`district\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`district\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`logo\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`logo\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`province\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`province\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`country\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`country\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`city\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`city\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`address\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`address\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`phone\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`phone\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`email\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`email\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`name\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD PRIMARY KEY (\`name\`)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` CHANGE \`modified\` \`modified\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` CHANGE \`creation\` \`creation\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` CHANGE \`is_gateway\` \`is_gateway\` tinyint NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` DROP INDEX \`IDX_beafdcdca7e045dfb0d68d370f\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` CHANGE \`modified\` \`modified\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` CHANGE \`creation\` \`creation\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`iot_dynamic_role\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`iot_dynamic_role\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`customer_id\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`customer_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`is_deactivated\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`is_deactivated\` tinyint(1) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`employee_id\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`employee_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`is_admin\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`is_admin\` tinyint(1) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`province\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`province\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`ward\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`ward\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`district\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`district\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`last_name\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`last_name\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`first_name\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`first_name\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`date_warranty\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`date_warranty\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`address\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`address\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`phone_number\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`phone_number\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`full_name\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`full_name\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`email\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`email\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`user_avatar\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`user_avatar\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`user_name\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`user_name\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP INDEX \`IDX_72c84d7e5ad67e33989de07b8c\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`user_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD \`name\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD PRIMARY KEY (\`name\`)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` DROP COLUMN \`total_retry_send_email\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` ADD \`total_retry_send_email\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` DROP COLUMN \`reset_password_key\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` ADD \`reset_password_key\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` DROP INDEX \`IDX_e88c7a238c02307fa55aa10e6a\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` ADD \`user_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` DROP COLUMN \`password\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` ADD \`password\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` DROP COLUMN \`enable\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` ADD \`enable\` tinyint(1) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` ADD \`name\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` ADD PRIMARY KEY (\`name\`)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` CHANGE \`show_chart\` \`show_chart\` tinyint(1) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` CHANGE \`data_type\` \`data_type\` enum ('Bool', 'Value', 'Enum', 'Raw', 'String', 'Group Break', 'Tab Break', 'IP', 'Checkbox-bit') NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` CHANGE \`modified\` \`modified\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` CHANGE \`creation\` \`creation\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` CHANGE \`is_default\` \`is_default\` tinyint(1) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` CHANGE \`modified\` \`modified\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` CHANGE \`creation\` \`creation\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`end_time\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`end_time\` time NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`start_time\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`start_time\` time NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`end_time\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`end_time\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`start_time\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`start_time\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`modified\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`modified\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`creation\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD \`creation\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` CHANGE \`status\` \`status\` enum ('running', 'stopped', 'finished', '') NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` CHANGE \`is_deleted\` \`is_deleted\` tinyint NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` CHANGE \`type\` \`type\` enum ('', 'circulate', 'period', 'fixed', 'interval') NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` CHANGE \`enable\` \`enable\` tinyint NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` CHANGE \`modified\` \`modified\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` CHANGE \`creation\` \`creation\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` CHANGE \`is_deleted\` \`is_deleted\` tinyint NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` CHANGE \`is_from_local\` \`is_from_local\` int NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` CHANGE \`is_synced\` \`is_synced\` tinyint NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` CHANGE \`status\` \`status\` enum ('active', 'inactive') NOT NULL DEFAULT 'inactive'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` CHANGE \`schedule_count\` \`schedule_count\` int NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` CHANGE \`modified\` \`modified\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` CHANGE \`creation\` \`creation\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`isReceiveNotificationNoti\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`isReceiveConnectionNoti\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`test\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`developerRuleId\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`developerWebhookId\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`developerMode\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`packageId\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`zipCode\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`zipPostalCode\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`createdTime\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`customerName\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP INDEX \`IDX_34e197ebfce40659e171f68c58\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`modifiedBy\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`deleted\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`idx\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`docstatus\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`owner\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`modified_by\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`_liked_by\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`_assign\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`_comments\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` DROP COLUMN \`_user_tags\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` DROP COLUMN \`customer_id\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` DROP COLUMN \`deleted\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` DROP COLUMN \`idx\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` DROP COLUMN \`docstatus\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` DROP COLUMN \`owner\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` DROP COLUMN \`modified_by\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` DROP COLUMN \`_liked_by\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` DROP COLUMN \`_assign\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` DROP COLUMN \`_comments\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` DROP COLUMN \`_user_tags\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`role_label\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`user_type\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`deleted\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`idx\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`docstatus\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`owner\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`modified_by\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`_liked_by\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`_assign\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`_comments\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`_user_tags\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`modified\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP COLUMN \`creation\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` DROP COLUMN \`last_reset_password_key_generated_on\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` DROP COLUMN \`deleted\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` DROP COLUMN \`idx\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` DROP COLUMN \`docstatus\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` DROP COLUMN \`owner\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` DROP COLUMN \`modified_by\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` DROP COLUMN \`_liked_by\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` DROP COLUMN \`_assign\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` DROP COLUMN \`_comments\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` DROP COLUMN \`_user_tags\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` DROP COLUMN \`modified\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` DROP COLUMN \`creation\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` DROP COLUMN \`deleted\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` DROP COLUMN \`idx\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` DROP COLUMN \`docstatus\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` DROP COLUMN \`owner\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` DROP COLUMN \`modified_by\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` DROP COLUMN \`_liked_by\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` DROP COLUMN \`_assign\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` DROP COLUMN \`_comments\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` DROP COLUMN \`_user_tags\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` DROP COLUMN \`deleted\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` DROP COLUMN \`idx\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` DROP COLUMN \`docstatus\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` DROP COLUMN \`owner\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` DROP COLUMN \`modified_by\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` DROP COLUMN \`_liked_by\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` DROP COLUMN \`_assign\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` DROP COLUMN \`_comments\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_profile\` DROP COLUMN \`_user_tags\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`deleted\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`idx\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`docstatus\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`owner\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`modified_by\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`_liked_by\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`_assign\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`_comments\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP COLUMN \`_user_tags\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` DROP COLUMN \`deleted\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` DROP COLUMN \`idx\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` DROP COLUMN \`docstatus\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` DROP COLUMN \`owner\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` DROP COLUMN \`modified_by\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` DROP COLUMN \`_liked_by\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` DROP COLUMN \`_assign\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` DROP COLUMN \`_comments\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` DROP COLUMN \`_user_tags\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` DROP COLUMN \`deleted\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` DROP COLUMN \`idx\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` DROP COLUMN \`docstatus\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` DROP COLUMN \`owner\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` DROP COLUMN \`modified_by\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` DROP COLUMN \`_liked_by\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` DROP COLUMN \`_assign\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` DROP COLUMN \`_comments\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_plan\` DROP COLUMN \`_user_tags\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`zip_code\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`developer_mode\` tinyint(1) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`customer_name\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer\` ADD \`created_time\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` ADD \`last_reset_password_key\` datetime NULL`);
        await queryRunner.query(`DROP TABLE \`device_offline_automation_intents\``);
        await queryRunner.query(`DROP TABLE \`tabiot_dynamic_role\``);
        await queryRunner.query(`DROP TABLE \`customer_login_sessions\``);
        await queryRunner.query(`CREATE UNIQUE INDEX \`device_id\` ON \`tabiot_device_telemetry\` (\`device_id\`, \`timestamp\`, \`key_name\`)`);
        await queryRunner.query(`CREATE INDEX \`device_profile_id\` ON \`tabiot_device\` (\`device_profile_id\`)`);
        await queryRunner.query(`CREATE INDEX \`customer_id\` ON \`tabiot_customer_user\` (\`customer_id\`)`);
        await queryRunner.query(`CREATE INDEX \`user_id\` ON \`tabiot_customer_user_credentials\` (\`user_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`idx_identifier\` ON \`tabiot_production_function\` (\`identifier\`)`);
        await queryRunner.query(`CREATE INDEX \`device_profile_id\` ON \`tabiot_production_function\` (\`device_profile_id\`)`);
        await queryRunner.query(`CREATE INDEX \`device_id\` ON \`tabiot_schedule\` (\`device_id\`)`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_telemetry\` ADD CONSTRAINT \`tabiot_device_telemetry_ibfk_1\` FOREIGN KEY (\`device_id\`) REFERENCES \`tabiot_device\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` ADD CONSTRAINT \`tabiot_device_ibfk_1\` FOREIGN KEY (\`device_profile_id\`) REFERENCES \`tabiot_device_profile\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD CONSTRAINT \`tabiot_customer_user_ibfk_1\` FOREIGN KEY (\`customer_id\`) REFERENCES \`tabiot_customer\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` ADD CONSTRAINT \`tabiot_customer_user_credentials_ibfk_1\` FOREIGN KEY (\`user_id\`) REFERENCES \`tabiot_customer_user\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` ADD CONSTRAINT \`tabiot_production_function_ibfk_1\` FOREIGN KEY (\`device_profile_id\`) REFERENCES \`tabiot_device_profile\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD CONSTRAINT \`fk_schedule_id\` FOREIGN KEY (\`schedule_id\`) REFERENCES \`tabiot_schedule\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` ADD CONSTRAINT \`tabiot_schedule_ibfk_1\` FOREIGN KEY (\`device_id\`) REFERENCES \`tabiot_device\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` ADD CONSTRAINT \`fk_plan_id\` FOREIGN KEY (\`schedule_plan_id\`) REFERENCES \`tabiot_schedule_plan\`(\`name\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
