import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrate1766645053000 implements MigrationInterface {
    name = 'Migrate1766645053000'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`tabiot_trip_accumulation\` (\`id\` int NOT NULL AUTO_INCREMENT, \`trip_id\` varchar(36) NOT NULL, \`device_id\` varchar(36) NOT NULL, \`sensor_key\` varchar(20) NOT NULL COMMENT 'fs01, fs02, fs03, fs04, fs05, fs06', \`total_volume_m3\` decimal(12,6) NOT NULL COMMENT 'Total accumulated volume in m³' DEFAULT '0.000000', \`total_volume_tons\` decimal(12,6) NOT NULL COMMENT 'Total accumulated volume in tons' DEFAULT '0.000000', \`oil_profile_id\` varchar(50) NULL, \`current_density\` decimal(8,2) NULL COMMENT 'Current density in kg/m³', \`last_update_time\` bigint NULL COMMENT 'Last update timestamp in milliseconds', \`sample_count\` int NOT NULL COMMENT 'Number of samples accumulated' DEFAULT '0', \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX \`IDX_f873f3618a91e280ed900364f8\` (\`device_id\`), INDEX \`IDX_b02dde4c4b596147fa13ea4ad1\` (\`trip_id\`), UNIQUE INDEX \`unique_trip_sensor\` (\`trip_id\`, \`sensor_key\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tabiot_trip\` (\`id\` varchar(36) NOT NULL, \`device_id\` varchar(36) NOT NULL, \`trip_name\` varchar(100) NULL, \`start_time\` bigint NOT NULL COMMENT 'Unix timestamp in milliseconds', \`end_time\` bigint NULL COMMENT 'Unix timestamp in milliseconds', \`status\` enum ('ACTIVE', 'COMPLETED', 'CANCELLED') NOT NULL DEFAULT 'ACTIVE', \`notes\` text NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp NULL, INDEX \`IDX_66e186e7803aa3ba951416a15d\` (\`device_id\`, \`status\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tabiot_oil_profile\` (\`creation\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), \`modified\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`_user_tags\` text NULL, \`_comments\` text NULL, \`_assign\` text NULL, \`_liked_by\` text NULL, \`modified_by\` varchar(140) NULL, \`owner\` varchar(140) NULL, \`docstatus\` smallint NOT NULL DEFAULT '0', \`idx\` bigint NOT NULL DEFAULT '0', \`deleted\` datetime(6) NULL, \`name\` varchar(255) NOT NULL, \`device_id\` varchar(255) NOT NULL, \`machine_type\` enum ('BOILER', 'MAIN_ENGINE', 'GENERATOR_HFO', 'GENERATOR_DO') NOT NULL COMMENT 'Machine type: BOILER (fs01), MAIN_ENGINE (fs02-fs03), GENERATOR_HFO (fs03-fs04), GENERATOR_DO (fs05-fs06)', \`oil_type\` enum ('DO', 'FO') NOT NULL COMMENT 'Oil type: DO (Diesel Oil), FO (Fuel Oil)', \`operating_temperature\` float NOT NULL COMMENT 'Operating temperature in Celsius', \`density\` float NOT NULL COMMENT 'Density in kg/m³ (SI unit)', \`label\` varchar(255) NULL, \`is_active\` tinyint NOT NULL COMMENT '1 if this is the active profile for the device' DEFAULT '0', \`description\` text NULL, \`deleted_at\` datetime NULL COMMENT 'Soft delete timestamp - profile is hidden but data preserved', INDEX \`IDX_ab43fa0de70aaf7dfa27274abb\` (\`device_id\`, \`machine_type\`, \`is_active\`), PRIMARY KEY (\`name\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tabiot_flow_checkpoint\` (\`id\` int NOT NULL AUTO_INCREMENT, \`device_id\` varchar(255) NOT NULL COMMENT 'Device ID', \`sensor_key\` varchar(20) NOT NULL COMMENT 'TFS sensor key: tfs01, tfs02, tfs03, tfs04, tfs05, tfs06', \`checkpoint_type\` varchar(20) NOT NULL COMMENT 'Checkpoint type: trip or hourly', \`last_tfs_value\` decimal(12,4) NOT NULL COMMENT 'Last TFS value read from PLC (m³)' DEFAULT '0.0000', \`last_update_time\` bigint NOT NULL COMMENT 'Timestamp when checkpoint was last updated (ms)', \`metadata\` text NULL COMMENT 'Additional metadata (JSON)', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_17436394560fee96432fa193bc\` (\`sensor_key\`), INDEX \`IDX_5d7a7bb38842db249e04d38e8a\` (\`device_id\`), UNIQUE INDEX \`idx_checkpoint_lookup\` (\`device_id\`, \`sensor_key\`, \`checkpoint_type\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tabiot_flow_accumulation\` (\`id\` int NOT NULL AUTO_INCREMENT, \`device_id\` varchar(255) NOT NULL, \`sensor_key\` varchar(255) NOT NULL COMMENT 'Sensor key: fs01, fs02, fs03, fs04, fs05, fs06', \`hour_start\` datetime NOT NULL COMMENT 'Hour start timestamp (e.g., 2025-01-01 00:00:00)', \`hour_end\` datetime NOT NULL COMMENT 'Hour end timestamp (e.g., 2025-01-01 01:00:00)', \`avg_flow_m3h\` float NOT NULL COMMENT 'Average flow rate in m3/h during this hour', \`accumulated_m3\` float NOT NULL COMMENT 'Accumulated volume in m3 for this hour', \`accumulated_tons\` float NOT NULL COMMENT 'Accumulated volume in tons for this hour (m3 * density)', \`oil_profile_id\` varchar(255) NOT NULL COMMENT 'Oil profile ID used for this calculation', \`density_used\` float NOT NULL COMMENT 'Density value in kg/m³ used for tons calculation (snapshot from profile)', \`sample_count\` int NOT NULL COMMENT 'Number of telemetry samples used in this hour calculation', \`first_sample_ts\` bigint NOT NULL COMMENT 'Timestamp of first sample in this hour (ms)', \`last_sample_ts\` bigint NOT NULL COMMENT 'Timestamp of last sample in this hour (ms)', \`created_at\` datetime NOT NULL COMMENT 'When this record was created' DEFAULT CURRENT_TIMESTAMP, INDEX \`IDX_22d0d5be04c56c7f4cc531ebdf\` (\`sensor_key\`, \`hour_start\`), INDEX \`IDX_a95896aa88bf37112d3a4698f1\` (\`device_id\`, \`hour_start\`), UNIQUE INDEX \`IDX_6d5c6872ca42a941cc0ff5fbfa\` (\`device_id\`, \`sensor_key\`, \`hour_start\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tabiot_thingsboard_telemetry_queue\` (\`id\` int NOT NULL AUTO_INCREMENT, \`device_id\` varchar(255) NOT NULL, \`device_token\` varchar(255) NOT NULL, \`idempotency_key\` varchar(36) NOT NULL, \`payload\` json NOT NULL, \`timestamp\` bigint NOT NULL, \`retry_count\` int NOT NULL DEFAULT '0', \`max_retries\` int NOT NULL DEFAULT '3', \`status\` enum ('pending', 'retrying', 'failed', 'permanently_failed', 'success') NOT NULL DEFAULT 'pending', \`last_error\` text NULL, \`last_retry_at\` bigint NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`idx_device_id\` (\`device_id\`), INDEX \`idx_idempotency_key\` (\`idempotency_key\`), INDEX \`idx_status\` (\`status\`), INDEX \`idx_retry\` (\`status\`, \`retry_count\`, \`last_retry_at\`), UNIQUE INDEX \`IDX_e56bde5fbda227d8a7f30182f9\` (\`idempotency_key\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tabiot_coil_tracking_session\` (\`creation\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), \`modified\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`_user_tags\` text NULL, \`_comments\` text NULL, \`_assign\` text NULL, \`_liked_by\` text NULL, \`modified_by\` varchar(140) NULL, \`owner\` varchar(140) NULL, \`docstatus\` smallint NOT NULL DEFAULT '0', \`idx\` bigint NOT NULL DEFAULT '0', \`deleted\` datetime(6) NULL, \`name\` varchar(140) NOT NULL, \`tracking_key\` varchar(100) NOT NULL, \`coil_key\` varchar(100) NOT NULL, \`board_id\` varchar(50) NULL, \`device_id\` varchar(140) NULL, \`start_time\` datetime NOT NULL, \`end_time\` datetime NULL, \`duration_seconds\` int NULL, \`status\` enum ('active', 'completed') NOT NULL DEFAULT 'active', \`start_snapshot\` json NULL, \`end_snapshot\` json NULL, INDEX \`IDX_9469954723661c61a8ac3813b8\` (\`board_id\`), INDEX \`IDX_b98698c453f24d37151b7c3585\` (\`start_time\`), INDEX \`IDX_6b73bff7de2f046e920fc50e66\` (\`device_id\`, \`status\`), INDEX \`IDX_7c3c6c2a0c4a1e900e8bc2e7d8\` (\`coil_key\`), INDEX \`IDX_19cf71b6a79935f6d28cd4766f\` (\`tracking_key\`), PRIMARY KEY (\`name\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`tabiot_dynamic_role\` ADD CONSTRAINT \`FK_2dc9693c049f8f5d16128500584\` FOREIGN KEY (\`iot_customer\`) REFERENCES \`tabiot_customer\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customer_login_sessions\` ADD CONSTRAINT \`FK_6796fe0549c819adab8f5154e46\` FOREIGN KEY (\`user_id\`) REFERENCES \`tabiot_customer_user\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` ADD CONSTRAINT \`FK_e88c7a238c02307fa55aa10e6ab\` FOREIGN KEY (\`user_id\`) REFERENCES \`tabiot_customer_user\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_notification\` ADD CONSTRAINT \`FK_c99b725dfb7b39d1aaa56bb6c99\` FOREIGN KEY (\`customer_id\`) REFERENCES \`tabiot_customer\`(\`name\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_notification\` ADD CONSTRAINT \`FK_e9eb6e0885ff8ee6588f65b0883\` FOREIGN KEY (\`customer_user\`) REFERENCES \`tabiot_customer_user\`(\`name\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD CONSTRAINT \`FK_f09e5990e0e92e85ebca9cdc7aa\` FOREIGN KEY (\`customer_id\`) REFERENCES \`tabiot_customer\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` ADD CONSTRAINT \`FK_780eb2884bf379e3f5744bdc0f1\` FOREIGN KEY (\`iot_dynamic_role\`) REFERENCES \`tabiot_dynamic_role\`(\`name\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` ADD CONSTRAINT \`FK_ca6a1941a27bc05174bddadc72a\` FOREIGN KEY (\`customer_id\`) REFERENCES \`tabiot_customer\`(\`name\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` ADD CONSTRAINT \`FK_803f66858054f399391d92e5f98\` FOREIGN KEY (\`device_profile_id\`) REFERENCES \`tabiot_device_profile\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_oil_profile\` ADD CONSTRAINT \`FK_5b648bbfb5cd7dd8cbba3e5d706\` FOREIGN KEY (\`device_id\`) REFERENCES \`tabiot_device\`(\`name\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` ADD CONSTRAINT \`FK_4f3fa51bdcb252c4869ac67c8ae\` FOREIGN KEY (\`schedule_plan_id\`) REFERENCES \`tabiot_schedule_plan\`(\`name\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD CONSTRAINT \`FK_82dbff0216b4f3ef0f543d2c07b\` FOREIGN KEY (\`schedule_id\`) REFERENCES \`tabiot_schedule\`(\`name\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` ADD CONSTRAINT \`FK_615b2e7ef1d8e04d0a8f30be73a\` FOREIGN KEY (\`customer_user\`) REFERENCES \`tabiot_customer_user\`(\`name\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` ADD CONSTRAINT \`FK_9fc556cd6d9ccfdd305e9f77f25\` FOREIGN KEY (\`device_profile_id\`) REFERENCES \`tabiot_device_profile\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_flow_accumulation\` ADD CONSTRAINT \`FK_b3036faad250c068295e44f6d06\` FOREIGN KEY (\`device_id\`) REFERENCES \`tabiot_device\`(\`name\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_flow_accumulation\` ADD CONSTRAINT \`FK_66ff2c3e68d0ebde3adbd24f38e\` FOREIGN KEY (\`oil_profile_id\`) REFERENCES \`tabiot_oil_profile\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_telemetry_latest\` ADD CONSTRAINT \`FK_47ac20dfac901a971b28b5d4ea3\` FOREIGN KEY (\`device_id\`) REFERENCES \`tabiot_device\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_telemetry\` ADD CONSTRAINT \`FK_26704df8a691ecb44c435e87ef9\` FOREIGN KEY (\`device_id\`) REFERENCES \`tabiot_device\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`device_offline_automation_intents\` ADD CONSTRAINT \`FK_d8226ed2510b2417ad5d78edb00\` FOREIGN KEY (\`device_id\`) REFERENCES \`tabiot_device\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`device_offline_automation_intents\` DROP FOREIGN KEY \`FK_d8226ed2510b2417ad5d78edb00\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_telemetry\` DROP FOREIGN KEY \`FK_26704df8a691ecb44c435e87ef9\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device_telemetry_latest\` DROP FOREIGN KEY \`FK_47ac20dfac901a971b28b5d4ea3\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_flow_accumulation\` DROP FOREIGN KEY \`FK_66ff2c3e68d0ebde3adbd24f38e\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_flow_accumulation\` DROP FOREIGN KEY \`FK_b3036faad250c068295e44f6d06\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_production_function\` DROP FOREIGN KEY \`FK_9fc556cd6d9ccfdd305e9f77f25\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP FOREIGN KEY \`FK_615b2e7ef1d8e04d0a8f30be73a\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule_log\` DROP FOREIGN KEY \`FK_82dbff0216b4f3ef0f543d2c07b\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_schedule\` DROP FOREIGN KEY \`FK_4f3fa51bdcb252c4869ac67c8ae\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_oil_profile\` DROP FOREIGN KEY \`FK_5b648bbfb5cd7dd8cbba3e5d706\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` DROP FOREIGN KEY \`FK_803f66858054f399391d92e5f98\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_device\` DROP FOREIGN KEY \`FK_ca6a1941a27bc05174bddadc72a\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP FOREIGN KEY \`FK_780eb2884bf379e3f5744bdc0f1\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user\` DROP FOREIGN KEY \`FK_f09e5990e0e92e85ebca9cdc7aa\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_notification\` DROP FOREIGN KEY \`FK_e9eb6e0885ff8ee6588f65b0883\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_notification\` DROP FOREIGN KEY \`FK_c99b725dfb7b39d1aaa56bb6c99\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_customer_user_credentials\` DROP FOREIGN KEY \`FK_e88c7a238c02307fa55aa10e6ab\``);
        await queryRunner.query(`ALTER TABLE \`customer_login_sessions\` DROP FOREIGN KEY \`FK_6796fe0549c819adab8f5154e46\``);
        await queryRunner.query(`ALTER TABLE \`tabiot_dynamic_role\` DROP FOREIGN KEY \`FK_2dc9693c049f8f5d16128500584\``);
        await queryRunner.query(`DROP INDEX \`IDX_19cf71b6a79935f6d28cd4766f\` ON \`tabiot_coil_tracking_session\``);
        await queryRunner.query(`DROP INDEX \`IDX_7c3c6c2a0c4a1e900e8bc2e7d8\` ON \`tabiot_coil_tracking_session\``);
        await queryRunner.query(`DROP INDEX \`IDX_6b73bff7de2f046e920fc50e66\` ON \`tabiot_coil_tracking_session\``);
        await queryRunner.query(`DROP INDEX \`IDX_b98698c453f24d37151b7c3585\` ON \`tabiot_coil_tracking_session\``);
        await queryRunner.query(`DROP INDEX \`IDX_9469954723661c61a8ac3813b8\` ON \`tabiot_coil_tracking_session\``);
        await queryRunner.query(`DROP TABLE \`tabiot_coil_tracking_session\``);
        await queryRunner.query(`DROP INDEX \`IDX_e56bde5fbda227d8a7f30182f9\` ON \`tabiot_thingsboard_telemetry_queue\``);
        await queryRunner.query(`DROP INDEX \`idx_retry\` ON \`tabiot_thingsboard_telemetry_queue\``);
        await queryRunner.query(`DROP INDEX \`idx_status\` ON \`tabiot_thingsboard_telemetry_queue\``);
        await queryRunner.query(`DROP INDEX \`idx_idempotency_key\` ON \`tabiot_thingsboard_telemetry_queue\``);
        await queryRunner.query(`DROP INDEX \`idx_device_id\` ON \`tabiot_thingsboard_telemetry_queue\``);
        await queryRunner.query(`DROP TABLE \`tabiot_thingsboard_telemetry_queue\``);
        await queryRunner.query(`DROP INDEX \`IDX_6d5c6872ca42a941cc0ff5fbfa\` ON \`tabiot_flow_accumulation\``);
        await queryRunner.query(`DROP INDEX \`IDX_a95896aa88bf37112d3a4698f1\` ON \`tabiot_flow_accumulation\``);
        await queryRunner.query(`DROP INDEX \`IDX_22d0d5be04c56c7f4cc531ebdf\` ON \`tabiot_flow_accumulation\``);
        await queryRunner.query(`DROP TABLE \`tabiot_flow_accumulation\``);
        await queryRunner.query(`DROP INDEX \`idx_checkpoint_lookup\` ON \`tabiot_flow_checkpoint\``);
        await queryRunner.query(`DROP INDEX \`IDX_5d7a7bb38842db249e04d38e8a\` ON \`tabiot_flow_checkpoint\``);
        await queryRunner.query(`DROP INDEX \`IDX_17436394560fee96432fa193bc\` ON \`tabiot_flow_checkpoint\``);
        await queryRunner.query(`DROP TABLE \`tabiot_flow_checkpoint\``);
        await queryRunner.query(`DROP INDEX \`IDX_ab43fa0de70aaf7dfa27274abb\` ON \`tabiot_oil_profile\``);
        await queryRunner.query(`DROP TABLE \`tabiot_oil_profile\``);
        await queryRunner.query(`DROP INDEX \`IDX_66e186e7803aa3ba951416a15d\` ON \`tabiot_trip\``);
        await queryRunner.query(`DROP TABLE \`tabiot_trip\``);
        await queryRunner.query(`DROP INDEX \`unique_trip_sensor\` ON \`tabiot_trip_accumulation\``);
        await queryRunner.query(`DROP INDEX \`IDX_b02dde4c4b596147fa13ea4ad1\` ON \`tabiot_trip_accumulation\``);
        await queryRunner.query(`DROP INDEX \`IDX_f873f3618a91e280ed900364f8\` ON \`tabiot_trip_accumulation\``);
        await queryRunner.query(`DROP TABLE \`tabiot_trip_accumulation\``);
    }

}
