/**
 * @fileoverview Device validator - Generated by VIIS API Generator
 */

import { Service } from 'typedi';
import { BaseValidator } from './base.validator';
import { CreateDeviceDto, UpdateDeviceDto, DeviceQueryDto } from '../dto/device.dto';

@Service()
export class DeviceValidator extends BaseValidator {
    /**
     * Validate create device request
     */
    async validateCreate(data: any): Promise<CreateDeviceDto> {
        return this.validate(CreateDeviceDto, data);
    }

    /**
     * Validate update device request
     */
    async validateUpdate(data: any): Promise<UpdateDeviceDto> {
        return this.validate(UpdateDeviceDto, data);
    }

    /**
     * Validate query parameters
     */
    async validateDeviceQuery(data: any): Promise<DeviceQueryDto> {
        return this.validate(DeviceQueryDto, data);
    }
}