/**
 * @fileoverview Device DTOs - Generated by VIIS API Generator
 */

import { IsString, IsNotEmpty, IsOptional } from 'class-validator';

export class CreateDeviceDto {
    @IsString()
    @IsNotEmpty({ message: 'Name is required' })
    name: string;

    // TODO: Add validation decorators for your properties
}

export class UpdateDeviceDto {
    @IsString()
    @IsOptional()
    name?: string;

    // TODO: Add validation decorators for your properties
}

export class DeviceQueryDto {
    @IsOptional()
    @IsString()
    search?: string;

    // TODO: Add query parameters for filtering
}