/**
 * @fileoverview Tung DTOs - Generated by VIIS API Generator
 */

import { IsString, IsNotEmpty, IsOptional } from 'class-validator';

export class CreateTungDto {
    @IsString()
    @IsNotEmpty({ message: 'Name is required' })
    name: string;

    @IsString()
    @IsOptional()
    description?: string;

    @IsString()
    @IsOptional()
    status?: string;

    // TODO: Add validation decorators for your properties
}

export class UpdateTungDto {
    @IsString()
    @IsOptional()
    name?: string;

    @IsString()
    @IsOptional()
    description?: string;

    @IsString()
    @IsOptional()
    status?: string;

    // TODO: Add validation decorators for your properties
}

export class TungQueryDto {
    @IsOptional()
    @IsString()
    search?: string;

    @IsOptional()
    @IsString()
    status?: string;

    // TODO: Add query parameters for filtering
}